
#this erlang image was made using debian stretch
#more info see: https://hub.docker.com/_/erlang
FROM erlang:19

LABEL maintainer="Philipp B. Costa"

# Create and define the container's working directory.
WORKDIR /home/app